Enable 32-bit Windows build in CircleCI
chfast/intx pull request #283
Opened 2023-01-04 15:06 UTC by axic

This fixes a build failure. [`_umul128` is x64 only](https://learn.microsoft.com/en-us/cpp/intrinsics/umul128?view=msvc-170), so [using `_M_X64`](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170) for checking that.

2023-01-05 21:14 UTC, axic commented
Will squash the 3rd and 1st commit, but left it to show the build failure.

2023-01-24 23:05 UTC, chfast approved these changes

2023-01-24 23:10 UTC, chfast requested changes

2023-01-24 23:10 UTC, chfast commented on circle.yml
> +            cd ~/build
Use `working_directory: ~/build`

2023-01-24 23:23 UTC, merged